/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorPropiedad;
import controlador.ControladorUsuario;

/**
 *
 * @author nataliasabogalrada
 */
public class VentanaPrincipalEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEmpleado
     */
    ControladorUsuario userController;
    ControladorPropiedad propiedadController;

    public VentanaPrincipalEmpleado(ControladorUsuario userController,ControladorPropiedad propiedadController) {
        initComponents();
        this.userController = userController;
        this.propiedadController = propiedadController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPropiedadesActivas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnGestionarPropiedades = new javax.swing.JButton();
        btnAgendarVisita = new javax.swing.JButton();
        btnHistorialEmpleado = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLogIN = new javax.swing.JMenuItem();
        menuPopiedadesAct = new javax.swing.JMenu();
        menuItemPropiedadesActivas = new javax.swing.JMenuItem();

        btnPropiedadesActivas.setText("Propiedaes Activas");
        btnPropiedadesActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedadesActivasActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Shree Devanagari 714", 1, 24))); // NOI18N

        btnGestionarPropiedades.setText("Gestionar Propiedades");
        btnGestionarPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarPropiedadesActionPerformed(evt);
            }
        });

        btnAgendarVisita.setText("Agendar Visita");
        btnAgendarVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarVisitaActionPerformed(evt);
            }
        });

        btnHistorialEmpleado.setText("Historial Propiedades");
        btnHistorialEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgendarVisita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionarPropiedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHistorialEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnGestionarPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAgendarVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnHistorialEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jMenu1.setText("X");
        jMenu1.setActionCommand("X");
        jMenu1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        menuLogIN.setText("LogIn");
        menuLogIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogINActionPerformed(evt);
            }
        });
        jMenu1.add(menuLogIN);

        jMenuBar1.add(jMenu1);

        menuPopiedadesAct.setText("Propiedades Activas");

        menuItemPropiedadesActivas.setText("Propiedades Activas");
        menuItemPropiedadesActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPropiedadesActivasActionPerformed(evt);
            }
        });
        menuPopiedadesAct.add(menuItemPropiedadesActivas);

        jMenuBar1.add(menuPopiedadesAct);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionarPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPropiedadesActionPerformed
        VentanaGestionarPropiedadesEmpleado empleado = new VentanaGestionarPropiedadesEmpleado(userController, propiedadController);
        empleado.setVisible(true);
        empleado.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnGestionarPropiedadesActionPerformed

    private void btnAgendarVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarVisitaActionPerformed
        VentanaAgendarVisita visita = new VentanaAgendarVisita(userController, propiedadController);
        visita.setVisible(true);
        visita.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnAgendarVisitaActionPerformed

    private void menuLogINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogINActionPerformed
        VentanaLogIn login = new VentanaLogIn(userController, propiedadController);
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menuLogINActionPerformed

    private void btnPropiedadesActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedadesActivasActionPerformed

    }//GEN-LAST:event_btnPropiedadesActivasActionPerformed

    private void menuItemPropiedadesActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPropiedadesActivasActionPerformed
        VentanaPropiedadesActivasEmpleado propiedades = new VentanaPropiedadesActivasEmpleado(userController, propiedadController);
        propiedades.setVisible(true);
        propiedades.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menuItemPropiedadesActivasActionPerformed

    private void btnHistorialEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialEmpleadoActionPerformed
        VentanaHistorialPropiedadesEmpleado empleado = new VentanaHistorialPropiedadesEmpleado(userController, propiedadController);
        empleado.setVisible(true);
        empleado.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnHistorialEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalEmpleado(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendarVisita;
    private javax.swing.JButton btnGestionarPropiedades;
    private javax.swing.JButton btnHistorialEmpleado;
    private javax.swing.JButton btnPropiedadesActivas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem menuItemPropiedadesActivas;
    private javax.swing.JMenuItem menuLogIN;
    private javax.swing.JMenu menuPopiedadesAct;
    // End of variables declaration//GEN-END:variables
}
